# Deploy container image to OpenShift

pool:
  name: lab

steps:
- task: oc-cmd@3
  displayName: OpenShift Deploy
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-sandbox'
    cmd: 'oc new-app --image=quay.io/dan_elder/syslogng --name=syslogng'