# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: syslogng

pool: 
  name: lab

steps:

- task: AzureKeyVault@2
  displayName: "Checkout secrets"
  inputs:
    azureSubscription: 'syslogng-pipeline-secrets'
    KeyVaultName: 'syslogng-keyvault'
    SecretsFilter: '*'
    RunAsPreJob: true

- task: CmdLine@2
  displayName: "Write eventhub auth token"
  inputs:
    script: 'echo $(eventhub-auth-token) > $(Build.SourcesDirectory)/etc/conf.d/eventhub-auth-token'

- task: CmdLine@2
  displayName: "Write Syslog-ng PE license"
  inputs:
    script: 'echo "$(license)" > $(Build.SourcesDirectory)/etc/license.txt'

- task: CmdLine@2
  displayName: "Write Syslog-ng PE certificate and key from vault"
  inputs:
    script: 'echo "$(syslogng-theelderfamily-org)" > $(Build.SourcesDirectory)/etc/cert.d/combined.pem'

- task: CmdLine@2
  displayName: "Clone syslog-ng-drivers to build environment"
  inputs:
    script: 'git clone https://github.com/danelder/syslog-ng-drivers.git $(Build.SourcesDirectory)/syslog-ng-drivers'

- task: Docker@1
  displayName: "Build syslog-ng container image"
  inputs:
    command: Build an image
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    arguments: '-t $(imageName):$(Build.BuildId) --build-arg RPM=$(RPM) --build-arg CACHEBUST=$(Build.BuildId)'

  env:
    RPM: $(RPM)

#- task: CmdLine@2
#  inputs:
#    script: 'docker push localhost:8080/admin/syslogng/latest'
