# Deploy container image to OpenShift

pool:
  vmImage: lab

steps:
- task: oc-cmd@3
  displayName: OpenShift whoami
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-sandbox'
    cmd: 'whoami'
