# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: syslogng

pool: 
  name: lab

steps:

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'syslogng-pipeline-secrets'
    KeyVaultName: 'syslogng-keyvault'
    SecretsFilter: '*'
    RunAsPreJob: true

- task: CmdLine@2
  inputs:
    script: 'echo $(eventhub-auth-token) > $(Build.SourcesDirectory)/etc/conf.d/eventhub-auth-token'

- task: CmdLine@2
  inputs:
    script: 'echo "$(license)" > $(Build.SourcesDirectory)/etc/license.txt'

- task: CmdLine@2
  inputs:
    script: 'echo "$(syslogng-theelderfamily-org)" > $(Build.SourcesDirectory)/etc/cert.d/combined.pem'

- task: CmdLine@2
  inputs:
    script: 'openssl x509 -in $(Build.SourcesDirectory)/etc/cert.d/combined.pem -out $(Build.SourcesDirectory)/etc/cert.d/certificate.crt'

- task: CmdLine@2
  inputs:
    script: 'openssl storeutl -keys $(Build.SourcesDirectory)/etc/cert.d/combined.pem > $(Build.SourcesDirectory)/etc/cert.d/certificate.key'

- task: Bash@3
  displayName: Build Container Image for syslogng-docker
  timeoutInMinutes: 5
  inputs:
    targetType: inline
    script: |
      podman build -f $(Build.SourcesDirectory)/Dockerfile -t $(imageName):$(Build.BuildId) --build-arg RPM=$(RPM) $(Build.SourcesDirectory)

- task: Docker@1
  displayName: Build an image
  inputs:
    command: Build an image
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    arguments: '-t $(imageName) --build-arg RPM=$(RPM)'
  env:
    RPM: $(RPM)

#- task: CmdLine@2
#  inputs:
#    script: 'docker push localhost:8080/admin/syslogng/latest'
