# Ubuntu Jammy
FROM ubuntu:jammy

# Upgrade system
RUN apt-get update && apt-get upgrade -y

# Install python dependency for driver
RUN apt install -y python3-netifaces

ARG VERSION=unknown

# Copy install package
COPY syslog-ng-jammy.deb /root/syslog-ng.deb

# Install syslog-ng
RUN yes | dpkg -i /root/syslog-ng.deb

# Cache volume for disk buffer and debug output
VOLUME [ "/tmp" ]

# Always force latest configuration
ARG CACHEBUST=1

# Copy syslog-ng configuration
COPY etc/ /opt/syslog-ng/etc/

# Copy syslog-ng configuration libraries
COPY scl/ /opt/syslog-ng/share/syslog-ng/include/scl/

# Startup syslog-ng
ENTRYPOINT /opt/syslog-ng/sbin/syslog-ng -F --no-caps -v -e