apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-ng
spec:
  replicas: 2
  selector:
    matchLabels:
      app: syslog-ng
  template:
    metadata:
      labels:
        app: syslog-ng
    spec:
      containers:
      - name: syslogng
        image: quay.io/dan_elder/syslogng:latest
        ports:
        - containerPort: 7024
        - containerPort: 7025
        - containerPort: 7026